//卡片数据 mock数据
import myImg from "../../assets/test.webp";
import myImg1 from "../../assets/test1.webp";
import avatar from "../../assets/avatar.webp";



const mockCardList = [
  {
    id: 1,
    poster: myImg,
    imgs: [myImg,myImg1],
    video: "",
    avatar: avatar,
    title: "主打性价比的iqoo手机都要用不起了",
    auth: "小镇出海",
    like: 100,
    collect: 20,
    content: "iqoo11pro现在都要4000多了，这谁顶的住",
    desc: ["让数码薯看看", "一起聊数码", "大v", "无厘头"],
    createDate: "06-30",
    localtion: "火星",
    commentsTotal: 230,
    comments: [
      {
        auth: "小王",
        avatar: avatar,
        createDate: "06-30",
        content: "谁买这玩意",
        location: "赛博坦星球",
        like: 200,
        childCommentsTotal: 3,
        childComments: [
          {
            auth: "小王",
            avatar: avatar,
            createDate: "06-30",
            content: "谁买这玩意",
            location: "赛博坦星球",
            like: 200,
            childCommentsTotal: 0,
            childComments: [],
          },
        ],
      },
      {
        auth: "小王",
        avatar: avatar,
        createDate: "06-30",
        content: "谁买这玩意",
        location: "赛博坦星球",
        like: 200,
        childCommentsTotal: 3,
        childComments: [
          {
            auth: "小王",
            avatar: avatar,
            createDate: "06-30",
            content: "谁买这玩意",
            location: "赛博坦星球",
            like: 200,
            childCommentsTotal: 0,
            childComments: [],
          },
        ],
      },
      {
        auth: "小王",
        avatar: avatar,
        createDate: "06-30",
        content: "谁买这玩意",
        location: "赛博坦星球",
        like: 200,
        childCommentsTotal: 3,
        childComments: [
          {
            auth: "小王",
            avatar: avatar,
            createDate: "06-30",
            content: "谁买这玩意",
            location: "赛博坦星球",
            like: 200,
            childCommentsTotal: 0,
            childComments: [],
          },
        ],
      },
      {
        auth: "小王",
        avatar: avatar,
        createDate: "06-30",
        content: "谁买这玩意",
        location: "赛博坦星球",
        like: 200,
        childCommentsTotal: 3,
        childComments: [
          {
            auth: "小王",
            avatar: avatar,
            createDate: "06-30",
            content: "谁买这玩意",
            location: "赛博坦星球",
            like: 200,
            childCommentsTotal: 0,
            childComments: [],
          },
        ],
      },
      {
        auth: "小王",
        avatar: avatar,
        createDate: "06-30",
        content: "谁买这玩意",
        location: "赛博坦星球",
        like: 200,
        childCommentsTotal: 3,
        childComments: [
          {
            auth: "小王",
            avatar: avatar,
            createDate: "06-30",
            content: "谁买这玩意",
            location: "赛博坦星球",
            like: 200,
            childCommentsTotal: 0,
            childComments: [],
          },
        ],
      },
      {
        auth: "小王",
        avatar: avatar,
        createDate: "06-30",
        content: "谁买这玩意",
        location: "赛博坦星球",
        like: 200,
        childCommentsTotal: 3,
        childComments: [
          {
            auth: "小王",
            avatar: avatar,
            createDate: "06-30",
            content: "谁买这玩意",
            location: "赛博坦星球",
            like: 200,
            childCommentsTotal: 0,
            childComments: [],
          },
        ],
      },
    ],
  },
  {
    id: 2,
    poster: myImg1,
    imgs: [myImg1],
    video: "",
    avatar: avatar,
    title: "主打性价比的iqoo手机都要用不起了",
    auth: "小镇出海",
    like: 100,
    collect: 20,
    content: "iqoo11pro现在都要4000多了，这谁顶的住",
    desc: ["让数码薯看看", "一起聊数码", "大v", "无厘头"],
    createDate: "06-30",
    localtion: "火星",
    commentsTotal: 230,
    comments: [
      {
        auth: "小王",
        avatar: avatar,
        createDate: "06-30",
        content: "谁买这玩意",
        location: "赛博坦星球",
        like: 200,
        childCommentsTotal: 3,
        childComments: [
          {
            auth: "小王",
            avatar: avatar,
            createDate: "06-30",
            content: "谁买这玩意",
            location: "赛博坦星球",
            like: 200,
            childCommentsTotal: 0,
            childComments: [],
          },
        ],
      },
    ],
  },
  {
    id: 1,
    poster: myImg,
    imgs: [myImg],
    video: "",
    avatar: avatar,
    title: "主打性价比的iqoo手机都要用不起了",
    auth: "小镇出海",
    like: 100,
    collect: 20,
    content: "iqoo11pro现在都要4000多了，这谁顶的住",
    desc: ["让数码薯看看", "一起聊数码", "大v", "无厘头"],
    createDate: "06-30",
    localtion: "火星",
    commentsTotal: 230,
    comments: [
      {
        auth: "小王",
        avatar: avatar,
        createDate: "06-30",
        content: "谁买这玩意",
        location: "赛博坦星球",
        like: 200,
        childCommentsTotal: 3,
        childComments: [
          {
            auth: "小王",
            avatar: avatar,
            createDate: "06-30",
            content: "谁买这玩意",
            location: "赛博坦星球",
            like: 200,
            childCommentsTotal: 0,
            childComments: [],
          },
        ],
      },
    ],
  },
  {
    id: 1,
    poster: myImg,
    imgs: [myImg],
    video: "",
    avatar: avatar,
    title: "主打性价比的iqoo手机都要用不起了",
    auth: "小镇出海",
    like: 100,
    collect: 20,
    content: "iqoo11pro现在都要4000多了，这谁顶的住",
    desc: ["让数码薯看看", "一起聊数码", "大v", "无厘头"],
    createDate: "06-30",
    localtion: "火星",
    commentsTotal: 230,
    comments: [
      {
        auth: "小王",
        avatar: avatar,
        createDate: "06-30",
        content: "谁买这玩意",
        location: "赛博坦星球",
        like: 200,
        childCommentsTotal: 3,
        childComments: [
          {
            auth: "小王",
            avatar: avatar,
            createDate: "06-30",
            content: "谁买这玩意",
            location: "赛博坦星球",
            like: 200,
            childCommentsTotal: 0,
            childComments: [],
          },
        ],
      },
    ],
  },
  {
    id: 1,
    poster: myImg,
    imgs: [myImg],
    video: "",
    avatar: avatar,
    title: "主打性价比的iqoo手机都要用不起了",
    auth: "小镇出海",
    like: 100,
    collect: 20,
    content: "iqoo11pro现在都要4000多了，这谁顶的住",
    desc: ["让数码薯看看", "一起聊数码", "大v", "无厘头"],
    createDate: "06-30",
    localtion: "火星",
    commentsTotal: 230,
    comments: [
      {
        auth: "小王",
        avatar: avatar,
        createDate: "06-30",
        content: "谁买这玩意",
        location: "赛博坦星球",
        like: 200,
        childCommentsTotal: 3,
        childComments: [
          {
            auth: "小王",
            avatar: avatar,
            createDate: "06-30",
            content: "谁买这玩意",
            location: "赛博坦星球",
            like: 200,
            childCommentsTotal: 0,
            childComments: [],
          },
        ],
      },
    ],
  },
  {
    id: 1,
    poster: myImg,
    imgs: [myImg],
    video: "",
    avatar: avatar,
    title: "主打性价比的iqoo手机都要用不起了",
    auth: "小镇出海",
    like: 100,
    collect: 20,
    content: "iqoo11pro现在都要4000多了，这谁顶的住",
    desc: ["让数码薯看看", "一起聊数码", "大v", "无厘头"],
    createDate: "06-30",
    localtion: "火星",
    commentsTotal: 230,
    comments: [
      {
        auth: "小王",
        avatar: avatar,
        createDate: "06-30",
        content: "谁买这玩意",
        location: "赛博坦星球",
        like: 200,
        childCommentsTotal: 3,
        childComments: [
          {
            auth: "小王",
            avatar: avatar,
            createDate: "06-30",
            content: "谁买这玩意",
            location: "赛博坦星球",
            like: 200,
            childCommentsTotal: 0,
            childComments: [],
          },
        ],
      },
    ],
  },
  {
    id: 1,
    poster: myImg,
    imgs: [myImg],
    video: "",
    avatar: avatar,
    title: "主打性价比的iqoo手机都要用不起了",
    auth: "小镇出海",
    like: 100,
    collect: 20,
    content: "iqoo11pro现在都要4000多了，这谁顶的住",
    desc: ["让数码薯看看", "一起聊数码", "大v", "无厘头"],
    createDate: "06-30",
    localtion: "火星",
    commentsTotal: 230,
    comments: [
      {
        auth: "小王",
        avatar: avatar,
        createDate: "06-30",
        content: "谁买这玩意",
        location: "赛博坦星球",
        like: 200,
        childCommentsTotal: 3,
        childComments: [
          {
            auth: "小王",
            avatar: avatar,
            createDate: "06-30",
            content: "谁买这玩意",
            location: "赛博坦星球",
            like: 200,
            childCommentsTotal: 0,
            childComments: [],
          },
        ],
      },
    ],
  },
  {
    id: 1,
    poster: myImg,
    imgs: [myImg],
    video: "",
    avatar: avatar,
    title: "主打性价比的iqoo手机都要用不起了",
    auth: "小镇出海",
    like: 100,
    collect: 20,
    content: "iqoo11pro现在都要4000多了，这谁顶的住",
    desc: ["让数码薯看看", "一起聊数码", "大v", "无厘头"],
    createDate: "06-30",
    localtion: "火星",
    commentsTotal: 230,
    comments: [
      {
        auth: "小王",
        avatar: avatar,
        createDate: "06-30",
        content: "谁买这玩意",
        location: "赛博坦星球",
        like: 200,
        childCommentsTotal: 3,
        childComments: [
          {
            auth: "小王",
            avatar: avatar,
            createDate: "06-30",
            content: "谁买这玩意",
            location: "赛博坦星球",
            like: 200,
            childCommentsTotal: 0,
            childComments: [],
          },
        ],
      },
    ],
  },
  {
    id: 1,
    poster: myImg,
    imgs: [myImg],
    video: "",
    avatar: avatar,
    title: "主打性价比的iqoo手机都要用不起了",
    auth: "小镇出海",
    like: 100,
    collect: 20,
    content: "iqoo11pro现在都要4000多了，这谁顶的住",
    desc: ["让数码薯看看", "一起聊数码", "大v", "无厘头"],
    createDate: "06-30",
    localtion: "火星",
    commentsTotal: 230,
    comments: [
      {
        auth: "小王",
        avatar: avatar,
        createDate: "06-30",
        content: "谁买这玩意",
        location: "赛博坦星球",
        like: 200,
        childCommentsTotal: 3,
        childComments: [
          {
            auth: "小王",
            avatar: avatar,
            createDate: "06-30",
            content: "谁买这玩意",
            location: "赛博坦星球",
            like: 200,
            childCommentsTotal: 0,
            childComments: [],
          },
        ],
      },
    ],
  },
  {
    id: 1,
    poster: myImg,
    imgs: [myImg],
    video: "",
    avatar: avatar,
    title: "主打性价比的iqoo手机都要用不起了",
    auth: "小镇出海",
    like: 100,
    collect: 20,
    content: "iqoo11pro现在都要4000多了，这谁顶的住",
    desc: ["让数码薯看看", "一起聊数码", "大v", "无厘头"],
    createDate: "06-30",
    localtion: "火星",
    commentsTotal: 230,
    comments: [
      {
        auth: "小王",
        avatar: avatar,
        createDate: "06-30",
        content: "谁买这玩意",
        location: "赛博坦星球",
        like: 200,
        childCommentsTotal: 3,
        childComments: [
          {
            auth: "小王",
            avatar: avatar,
            createDate: "06-30",
            content: "谁买这玩意",
            location: "赛博坦星球",
            like: 200,
            childCommentsTotal: 0,
            childComments: [],
          },
        ],
      },
    ],
  },
];
export default mockCardList
